name: SoulNode
options:
  bundleIdPrefix: com.busd777
targets:
  SoulNode:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: 
      - path: Sources
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSLocalNetworkUsageDescription: "Для подключения к slskd"
        UIBackgroundModes: [audio, fetch, processing]
