- name: Build Go Framework
        env:
          GOPROXY: https://proxy.golang.org,direct
          GOSUMDB: sum.golang.org
        run: |
          # ПРИНУДИТЕЛЬНО отключаем подмену протоколов и запросы пароля
          git config --global --unset url."git@github.com:".insteadOf || true
          git config --global url."https://github.com/".insteadOf "git@github.com:" || true
          export GIT_TERMINAL_PROMPT=0
          
          cd go
          # Очищаем кэш и подтягиваем модули
          go mod tidy
          
          # Устанавливаем принудительно bind
          go get golang.org/x/mobile/bind
          
          gomobile init
          mkdir -p ../Frameworks
          
          # Сборка с подробным логом
          gomobile bind -target=ios -v -o ../Frameworks/Node.xcframework ./node
